### ISSUE TITLE
Changing max_tokens default value to some higher value may be 512/1024

### ISSUE THREAD

**Issue by pranjaldoshi96** [langchain-ai/langchain-nvidia#34]
Default value of `max_tokens` is set to 16, which does not generate good response for most of the scenario. Setting it to something higher value similar to openai can be helpful. 

This is mostly my experience, obviously there might be other scenario where folks will prefer smaller values. Still 16 token does not even generate complete a sentence or two sometime.

Will love to hear your opinion on this.

**Comment by mattf** [comment]
same as #27
